apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    name: redis-app-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

